import{S as v,a as L,i as y}from"./assets/vendor-c145bea9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const w=new v(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0}),d=document.querySelector(".form"),m=document.querySelector(".gallery"),i=document.querySelector(".loader"),c=document.querySelector(".second-btn");let l=1,u=!1,p="";const x=L.create({baseURL:"https://pixabay.com/api/",params:{key:"41526940-8233d9bee139c8a54ba6bf59b",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40}});function q(s=[]){const r=s.reduce((a,{largeImageURL:o,webformatURL:e,tags:t,likes:n,views:g,comments:h,downloads:b})=>a+`<li class="gallery-item">
        <a href=${o}> 
          <img class="gallery-img" src =${e} alt=${t}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${n}</span></p>
          <p>Views: <span class="text-value">${g}</span></p>
          <p>Comments: <span class="text-value">${h}</span></p>
          <p>Downloads: <span class="text-value">${b}</span></p>
        </div>
       </li>`,"");m.insertAdjacentHTML("beforeend",r)}const S=async s=>{try{return(await x.get("",{params:s})).data}catch(r){throw new Error(r)}},f=async s=>{try{if(u)return;const{hits:a,totalHits:o}=await S({page:l,per_page:40,q:s});l>=Math.ceil(o/40)&&(u=!0),l+=1,q(a),a.length<40?c.style.display="none":c.style.display="block",w.refresh()}catch{y.error({position:"topRight",maxWidth:432,message:"Sorry, there are no images matching your search query. Please try again!"})}finally{i.style.display="none"}};d.addEventListener("submit",async s=>{if(s.preventDefault(),l=1,u=!1,m.innerHTML="",i.style.display="block",p=d.elements.search.value.trim(),!p){i.style.display="none";return}await f(p)});c.addEventListener("click",async s=>{s.preventDefault(),i.style.display="block";const r=d.elements.search.value.trim();await f(r);const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"}),u&&(c.style.display="none",y.info({position:"topRight",maxWidth:432,message:"We're sorry, but you've reached the end of search results."}))});
//# sourceMappingURL=commonHelpers.js.map
