import{S as b,a as v,i as d}from"./assets/vendor-c145bea9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const L=new b(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0}),l=document.querySelector(".form"),y=document.querySelector(".gallery"),p=document.querySelector(".loader"),c=document.querySelector(".second-btn");let i=1,u=!1;const x=v.create({baseURL:"https://pixabay.com/api/",params:{key:"41526940-8233d9bee139c8a54ba6bf59b",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40}});function w(s=[]){const t=s.reduce((a,{largeImageURL:o,webformatURL:e,tags:r,likes:n,views:f,comments:g,downloads:h})=>a+`<li class="gallery-item">
        <a href=${o}> 
          <img class="gallery-img" src =${e} alt=${r}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${n}</span></p>
          <p>Views: <span class="text-value">${f}</span></p>
          <p>Comments: <span class="text-value">${g}</span></p>
          <p>Downloads: <span class="text-value">${h}</span></p>
        </div>
       </li>`,"");y.insertAdjacentHTML("beforeend",t)}const q=async s=>{try{return(await x.get("",{params:s})).data}catch(t){throw new Error(t.statusText)}},m=async s=>{try{if(u)return;const{hits:a,totalHits:o}=await q({page:i,per_page:40,q:s});i>=Math.ceil(o/40)&&(u=!0),i+=1,w(a),c.style.display="block",L.refresh()}catch{d.error({position:"topRight",maxWidth:432,message:"Sorry, there are no images matching your search query. Please try again!"})}finally{p.style.display="none"}};l.addEventListener("submit",async s=>{s.preventDefault(),y.innerHTML="",p.style.display="block";let t="";l.elements.search.value.trim()!=t&&(i=1),t=l.elements.search.value.trim(),await m(t)});c.addEventListener("click",async s=>{s.preventDefault(),p.style.display="block";const t=l.elements.search.value.trim();await m(t);const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"}),u&&(c.style.display="none",d.info({position:"topRight",maxWidth:432,message:"We're sorry, but you've reached the end of search results."}))});
//# sourceMappingURL=commonHelpers.js.map
