import{S as v,a as L,i as y}from"./assets/vendor-c145bea9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const w=new v(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0}),d=document.querySelector(".form"),f=document.querySelector(".gallery"),i=document.querySelector(".loader"),c=document.querySelector(".second-btn");let u=1,p=!1,l="";const x=L.create({baseURL:"https://pixabay.com/api/",params:{key:"41526940-8233d9bee139c8a54ba6bf59b",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40}});function q(r=[]){const s=r.reduce((o,{largeImageURL:a,webformatURL:e,tags:t,likes:n,views:g,comments:h,downloads:b})=>o+`<li class="gallery-item">
        <a href=${a}> 
          <img class="gallery-img" src =${e} alt=${t}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${n}</span></p>
          <p>Views: <span class="text-value">${g}</span></p>
          <p>Comments: <span class="text-value">${h}</span></p>
          <p>Downloads: <span class="text-value">${b}</span></p>
        </div>
       </li>`,"");f.insertAdjacentHTML("beforeend",s)}const S=async r=>{try{return(await x.get("",{params:r})).data}catch(s){throw new Error(s)}},m=async r=>{try{if(p)return;const{hits:o,totalHits:a}=await S({page:u,q:r});u>=Math.ceil(a/40)?(c.style.display="none",p=!0):c.style.display="block",q(o),w.refresh()}catch{y.error({position:"topRight",maxWidth:432,message:"Sorry, there are no images matching your search query. Please try again!"})}finally{i.style.display="none"}};d.addEventListener("submit",async r=>{if(r.preventDefault(),u=1,p=!1,f.innerHTML="",i.style.display="block",l=d.elements.search.value.trim(),!l){i.style.display="none";return}await m(l)});c.addEventListener("click",async r=>{r.preventDefault(),i.style.display="block",u+=1,await m(l),k(),p&&(c.style.display="none",y.info({position:"topRight",maxWidth:432,message:"We're sorry, but you've reached the end of search results."}))});function k(){const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
